<?php
	$abbrevation = array("{W}","{U}","{B}","{R}","{G}","{S}","{C}","{1}","{2}","{3}","{4}","{5}",
							"{6}","{7}","{8}","{9}","{0}", "{X}", "{B/G}", "{B/R}", "{G/U}"
							, "{G/W}", "{R/G}", "{R/W}", "{U/B}", "{U/R}", "{W/B}", "{W/U}",
							"{W/P}","{U/P}","{B/P}","{R/P}","{G/P}", "{G/U/P}", "{T}", "{Q}");
	$manaReplace = array(
	"<img src = 'content/symbols/W.png' width = '24'>",
	"<img src = 'content/symbols/U.png' width = '24'>",
	"<img src = 'content/symbols/B.png' width = '24'>",
	"<img src = 'content/symbols/R.png' width = '24'>",
	"<img src = 'content/symbols/G.png' width = '24'>",
	"<img src = 'content/symbols/S.png' width = '24'>",
	"<img src = 'content/symbols/C.png' width = '24'>",
	"<img src = 'content/symbols/1.png' width = '24'>",
	"<img src = 'content/symbols/2.png' width = '24'>",
	"<img src = 'content/symbols/3.png' width = '24'>",
	"<img src = 'content/symbols/4.png' width = '24'>",
	"<img src = 'content/symbols/5.png' width = '24'>",
	"<img src = 'content/symbols/6.png' width = '24'>",
	"<img src = 'content/symbols/7.png' width = '24'>",
	"<img src = 'content/symbols/8.png' width = '24'>",
	"<img src = 'content/symbols/9.png' width = '24'>",
	"<img src = 'content/symbols/0.png' width = '24'>",
	"<img src = 'content/symbols/X.png' width = '24'>",
	"<img src = 'content/symbols/BG.png' width = '24'>",
	"<img src = 'content/symbols/BR.png' width = '24'>",
	"<img src = 'content/symbols/GU.png' width = '24'>",
	"<img src = 'content/symbols/GW.png' width = '24'>",
	"<img src = 'content/symbols/RG.png' width = '24'>",
	"<img src = 'content/symbols/RW.png' width = '24'>",
	"<img src = 'content/symbols/UB.png' width = '24'>",
	"<img src = 'content/symbols/UR.png' width = '24'>",
	"<img src = 'content/symbols/WB.png' width = '24'>",
	"<img src = 'content/symbols/WU.png' width = '24'>",
	"<img src = 'content/symbols/WP.png' width = '24'>",
	"<img src = 'content/symbols/UP.png' width = '24'>",
	"<img src = 'content/symbols/BP.png' width = '24'>",
	"<img src = 'content/symbols/RP.png' width = '24'>",
	"<img src = 'content/symbols/GP.png' width = '24'>",
	"<img src = 'content/symbols/GUP.png' width = '24'>");
	
	$symbolReplace = array(
	"<img src = 'content/symbols/W.png' width = '16'>",
	"<img src = 'content/symbols/U.png' width = '16'>",
	"<img src = 'content/symbols/B.png' width = '16'>",
	"<img src = 'content/symbols/R.png' width = '16'>",
	"<img src = 'content/symbols/G.png' width = '16'>",
	"<img src = 'content/symbols/S.png' width = '16'>",
	"<img src = 'content/symbols/C.png' width = '16'>",
	"<img src = 'content/symbols/1.png' width = '16'>",
	"<img src = 'content/symbols/2.png' width = '16'>",
	"<img src = 'content/symbols/3.png' width = '16'>",
	"<img src = 'content/symbols/4.png' width = '16'>",
	"<img src = 'content/symbols/5.png' width = '16'>",
	"<img src = 'content/symbols/6.png' width = '16'>",
	"<img src = 'content/symbols/7.png' width = '16'>",
	"<img src = 'content/symbols/8.png' width = '16'>",
	"<img src = 'content/symbols/9.png' width = '16'>",
	"<img src = 'content/symbols/0.png' width = '16'>",
	"<img src = 'content/symbols/X.png' width = '16'>",
	"<img src = 'content/symbols/BG.png' width = '16'>",
	"<img src = 'content/symbols/BR.png' width = '16'>",
	"<img src = 'content/symbols/GU.png' width = '16'>",
	"<img src = 'content/symbols/GW.png' width = '16'>",
	"<img src = 'content/symbols/RG.png' width = '16'>",
	"<img src = 'content/symbols/RW.png' width = '16'>",
	"<img src = 'content/symbols/UB.png' width = '16'>",
	"<img src = 'content/symbols/UR.png' width = '16'>",
	"<img src = 'content/symbols/WB.png' width = '16'>",
	"<img src = 'content/symbols/WU.png' width = '16'>",
	"<img src = 'content/symbols/WP.png' width = '16'>",
	"<img src = 'content/symbols/UP.png' width = '16'>",
	"<img src = 'content/symbols/BP.png' width = '16'>",
	"<img src = 'content/symbols/RP.png' width = '16'>",
	"<img src = 'content/symbols/GP.png' width = '16'>",
	"<img src = 'content/symbols/GUP.png' width = '16'>",
	"<img src = 'content/symbols/T.png' width = '16'>",
	"<img src = 'content/symbols/Q.png' width = '16'>"
	);
?>